---
abstract: 'PayPal Permissions'
author:
  - 'Fayland Lam <fayland@gmail.com>'
  - 'Mc Cheung'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-PayPal-Permissions
requires:
  Digest::HMAC_SHA1: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
resources:
  repository: git://github.com/fayland/p5-Business-PayPal-Permissions.git
version: 0.02
